version: '3.8'

services:
    django_server:
        build: .
        container_name: django_server
        command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        env_file:
            - .env
        environment:
            - DATABASE_HOST=postgres
            - REDIS_HOST=redis
        depends_on:
            - postgres
            - redis
        restart: always

    postgres:
        image: postgres:15-alpine
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

    redis:
        image: redis:7.0-alpine
        ports:
            - "6379:6379"
        restart: unless-stopped
        volumes:
            - redis_data:/data

volumes:
    postgres_data:
    redis_data:
